WebApplication3/Controllers/Test/TestController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;
using Newtonsoft.Json;

namespace WebApplication3.Controllers.Test
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            var model = new HomeModel
            {
                AvailableFruits = GetFruits()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(HomeModel model)
        {
            if (ModelState.IsValid)
            {
                var fruits = string.Join(",", model.SelectedFruits);

                // Save data to database, and redirect to Success page.

                return RedirectToAction("Success");
            }
            model.AvailableFruits = GetFruits();
            return View(model);
        }

        public ActionResult Success()
        {
            return View("Index");
        }

        protected IList<SelectListItem> GetFruits()
        {
            return new List<SelectListItem>
            {
                new SelectListItem {Text = "Apple", Value = "Apple"},
                new SelectListItem {Text = "Pear", Value = "Pear"},
                new SelectListItem {Text = "Banana", Value = "Banana"},
                new SelectListItem {Text = "Orange", Value = "Orange"},
            };
        }
    }
}

WebApplication3/Views/Test/Index.cshtml
@Model WebApplication3.Models.HomeModel
@using System.Web.UI.WebControls
@using WebApplication3.Code
@using WebApplication3.Models
@{
    @Scripts.Render("~/Scripts/jquery-1.10.2.js")
    @Scripts.Render("~/Scripts/bootstrap.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    if (Model == null)
    {
        Model.AvailableFruits = Utils.GetFruits();
    }
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    @using (Html.BeginForm("Index", "Test"))
    {
        foreach (var item in Model.AvailableFruits)
        {
            <div class="checkbox">
                <label>
                    <input type="checkbox"
                           name="SelectedFruits"
                           value="@item.Value" /> @item.Text
                </label>
            </div>
        }

        <div class="form-group text-center">
            <input type="submit" class="btn btn-primary" value="Submit" />
        </div>
    }
</div>
</body>
</html>